version: "3"

services:
  server:
    build: .
    command: python -u server/server.py
    ports:
      - "50051:50051"

  client_bot:
    build: .
    command: python client/client_bot.py localhost:50051
    network_mode: host
    deploy:
      replicas: 3
    depends_on:
      - server
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12
    ports:
      - "5672:5672"
