# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/mafia.proto\x12\x05mafia\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x14\n\x12\x44isconnectResponse\"\x11\n\x0fGetUsersRequest\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"D\n\x12GetSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x1a\n\x12is_session_present\x18\x02 \x01(\x08\x32\xdd\x01\n\x05Mafia\x12+\n\x07\x43onnect\x12\x0f.mafia.UserName\x1a\r.mafia.UserId\"\x00\x12\x38\n\nDisconnect\x12\r.mafia.UserId\x1a\x19.mafia.DisconnectResponse\"\x00\x12\x33\n\x08GetUsers\x12\x16.mafia.GetUsersRequest\x1a\x0b.mafia.User\"\x00\x30\x01\x12\x38\n\nGetSession\x12\r.mafia.UserId\x1a\x19.mafia.GetSessionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERNAME._serialized_start=28
  _USERNAME._serialized_end=52
  _USERID._serialized_start=54
  _USERID._serialized_end=74
  _DISCONNECTRESPONSE._serialized_start=76
  _DISCONNECTRESPONSE._serialized_end=96
  _GETUSERSREQUEST._serialized_start=98
  _GETUSERSREQUEST._serialized_end=115
  _USER._serialized_start=117
  _USER._serialized_end=149
  _GETSESSIONRESPONSE._serialized_start=151
  _GETSESSIONRESPONSE._serialized_end=219
  _MAFIA._serialized_start=222
  _MAFIA._serialized_end=443
# @@protoc_insertion_point(module_scope)
